on:
  schedule:
    - cron: '30/10 * * * *'
    # - cron: '0 1 1 1 1'

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@9f9a163f533fcbf8b3d9fe1bf5458e8c23502698
        with:
          url: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health

