on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Set current_branch variable
        run: echo "::set-output name=CURRENT_BRANCH::$(echo ${GITHUB_REF##*/})"
        id: set_current_branch
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: npm install 
        run: npm install  
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start-prod
          wait-on: http://localhost:5000
          command: npm run test:e2e
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ steps.set_current_branch.outputs.CURRENT_BRANCH == 'master' && contains(toJson(github.event.commits[0].message), '#skip') != true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: deploy on heroku
        if: ${{ github.event_name == 'push' && contains(toJson(github.event.commits[0].message), '#skip') != true }}
        uses: akhileshns/heroku-deploy@v3.12.12
        id: deploy
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "imran.pavel@gmail.com"
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: Notify deployment success
        uses: 8398a7/action-slack@c84a35cfa82a01f3733a3cbf5d5260123e55c2f9
        if: ${{ steps.deploy.outcome == 'success' }}
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author,took,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify pipeline failure
        uses: 8398a7/action-slack@c84a35cfa82a01f3733a3cbf5d5260123e55c2f9
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author,took,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
        
